from __future__ import annotations

from typing import Protocol

from app.features.search_run.domain.models import SearchRunRecord


class SearchRunRepository(Protocol):
    async def save(self, record: SearchRunRecord) -> None: ...
    async def get(self, run_id: str) -> SearchRunRecord | None: ...
    async def list_recent(self, *, limit: int = 50) -> list[SearchRunRecord]: ...
    async def count(self) -> int: ...
    async def aggregate(self) -> dict: ...
