"""Vietnamese ↔ English normalization helpers shared by the planner and demo index."""

from __future__ import annotations

VI_TO_EN: dict[str, list[str]] = {
    "nguoi": ["person"],
    "con nguoi": ["person"],
    "dan ong": ["man"],
    "dan ba": ["woman"],
    "phu nu": ["woman"],
    "tre em": ["child"],
    "con gai": ["girl"],
    "con trai": ["boy"],
    "xe dap": ["bicycle"],
    "xe may": ["motorcycle"],
    "o to": ["car"],
    "xe hoi": ["car"],
    "xe buyt": ["bus"],
    "may bay": ["airplane", "aircraft"],
    "tau": ["boat"],
    "thuyen": ["boat"],
    "tau thuyen": ["boat"],
    "thuyen buom": ["boat"],
    "xe lua": ["train"],
    "duong pho": ["street"],
    "ngoai duong": ["street"],
    "trong nha": ["indoor"],
    "ngoai troi": ["outdoor"],
    "ao do": ["red shirt", "shirt"],
    "ao xanh": ["blue shirt", "shirt"],
    "ao": ["shirt"],
    "quan ao": ["clothing"],
    "vay": ["dress"],
    "giay": ["footwear"],
    "mu": ["hat"],
    "tui": ["handbag"],
    "di bo": ["walking"],
    "dang di": ["riding"],
    "chay": ["running"],
    "nhay": ["jumping"],
    "boi": ["swimming"],
    "bay": ["flying"],
    "an": ["eating"],
    "nau an": ["cooking"],
    "choi": ["playing"],
    "ngu": ["sleeping"],
    "ngoi": ["sitting"],
    "dung": ["standing"],
    "cuoi": ["smiling"],
    "noi chuyen": ["talking"],
    "dien thoai": ["phone"],
    "may tinh": ["computer", "computer monitor"],
    "tv": ["television"],
    "sach": ["book"],
    "ghe": ["chair"],
    "ban": ["table"],
    "cua": ["door"],
    "cua so": ["window"],
    "cho": ["dog", "market"],
    "meo": ["cat"],
    "chim": ["bird"],
    "ca": ["fish"],
    "bo": ["cow"],
    "ngua": ["horse"],
    "cu": ["turtle"],
    "khi": ["monkey"],
    "gau": ["bear"],
    "tho": ["rabbit"],
    "dong vat": ["animal"],
    "thu": ["animal"],
    "vat nuoi": ["pet"],
    "thu hoang da": ["wildlife"],
    "hoang da": ["wildlife"],
    "hoang": ["wild"],
    "tu nhien": ["nature"],
    "cay": ["tree", "plant"],
    "cay coi": ["tree", "plant"],
    "cay xanh": ["tree"],
    "thuc vat": ["plant"],
    "hoa": ["flower"],
    "co": ["grass"],
    "do xe": ["parked"],
    "bai do xe": ["parking lot"],
    "bai dau xe": ["parking lot"],
    "nha": ["house"],
    "can ho": ["apartment"],
    "toa nha": ["building"],
    "song": ["river"],
    "bien": ["beach"],
    "nui": ["mountain"],
    "ho": ["lake"],
    "san bay": ["airport"],
    "tram xang": ["gas station"],
    "cong ty": ["office"],
    "truong hoc": ["school"],
    "benh vien": ["hospital"],
    "nha hang": ["restaurant"],
    "khach san": ["hotel"],
    "cua hang": ["store"],
    "cong vien": ["park"],
    "san vuon": ["garden"],
    "san": ["yard"],
    "be boi": ["swimming pool"],
}


_VIET_UNICODE = (
    "àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễ"
    "ìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữ"
    "ỳýỵỷỹđ"
)
_VIET_ASCII = (
    "aaaaaaaaaaaaaaaaa"
    "eeeeeeeeeee"
    "iiiiiooooooooooooooooouuuuuuuuuuuyyyyyd"
)


def normalize_ascii(text: str) -> str:
    replacements = str.maketrans(_VIET_UNICODE, _VIET_ASCII)
    return " ".join(text.lower().translate(replacements).split())
